import '../styles/main.scss';
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
  title: "Trouver son artisan",
  description: "Generated by Lyon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="page-wrapper">
        <Navbar/>
        <div className="content mb-5">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}