import "./globals.css";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Accueil from "./page";

export const metadata = {
  title: "Trouver son artisan",
  description: "Generated by Lyon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Trouver son artisan</title>
        <meta name="description" content="Generated by Lyon" />
      </head>
      <body>
        <Navbar/>
        <Accueil/>
        <Footer />
      </body>
    </html>
  );
}